### ISSUE TITLE
Where are the codes?

### ISSUE THREAD

**Issue by SihenZhang** [Correlated2/Correlated2#2]
I really want to use this mod. And I found here from the old repo. 
I saw that you commit 10 days ago. But there are no codes or releases that I can use. Jenkins is also 404...
So...I was confused that **where are the codes and releases?**

**Comment by jamierocks** [comment]
The mod no longer has publicly-viewable source, you can find the versions prior to 2.1 [here](https://github.com/unascribed/Correlated-Legacy). I don't think any releases have been made for 2.1 yet, and I'm not certain where the old releases are :S.

**Comment by CrankySupertoonArchive** [comment]
Jamie i downloaded a build but it seems like you cant download that build anymore. It was called correlated 2.1 and was after the github issues

**Comment by exaskye** [comment]
Old releases got deleted because I deleted the old repo while in a bad emotional state as a response to an argument I was having in IRC. I don't have archives of them, but can build them on request.

2.1 is closed source for a variety of personal mental health/motivational reasons I'm not interested in getting into. I'm giving access to dev builds of the mod based on this new closed source tree selectively upon request. When 2.2 rolls around I'm likely to make the mod open source again.
